export const exercises={
  'variables-types':exercise('profile-summary','Build a profile summary','בנו תקציר פרופיל','Create variables name, age and active. Set result to one formatted string: Maya | 24 | active','צרו משתנים בשם name, age ו-active. הכניסו אל result מחרוזת אחת: Maya | 24 | active','name = "Maya"\nage = 24\nactive = True\n\nresult = ""',[test('Exact result','תוצאה מדויקת','assert result == "Maya | 24 | active"'),test('Useful types','טיפוסים נכונים','assert isinstance(age, int) and isinstance(active, bool)')]),
  'conditions':exercise('shipping-price','Calculate shipping','חשבו מחיר משלוח','Implement shipping_cost(total, premium). Premium users or orders of 200 and above get free shipping. Otherwise return 20.','ממשו shipping_cost(total, premium). משתמשי Premium או הזמנות בסך 200 ומעלה מקבלים משלוח חינם. אחרת החזירו 20.','def shipping_cost(total, premium):\n    # Write your solution\n    pass',[test('Regular order','הזמנה רגילה','assert shipping_cost(100, False) == 20'),test('Large order','הזמנה גדולה','assert shipping_cost(200, False) == 0'),test('Premium user','משתמש Premium','assert shipping_cost(40, True) == 0')]),
  'loops':exercise('count-passed','Count passing scores','ספרו ציונים עוברים','Implement count_passed(scores). Return how many scores are 60 or higher.','ממשו count_passed(scores). החזירו כמה ציונים הם 60 ומעלה.','def count_passed(scores):\n    count = 0\n    # Write your loop\n    return count',[test('Mixed scores','ציונים מעורבים','assert count_passed([90, 55, 60, 42, 77]) == 3'),test('Empty list','רשימה ריקה','assert count_passed([]) == 0'),test('All failed','כולם נכשלו','assert count_passed([10, 20]) == 0')]),
  'collections':exercise('index-users','Index users by ID','מפתחו משתמשים לפי ID','Implement index_users(users). Return a dictionary mapping each id to its full user dictionary.','ממשו index_users(users). החזירו מילון שממפה כל id למילון המשתמש המלא.','def index_users(users):\n    # Write your solution\n    return {}',[test('Creates mapping','יוצר מיפוי','users=[{"id":1,"name":"Maya"},{"id":2,"name":"Noa"}]; assert index_users(users)=={1:users[0],2:users[1]}'),test('Empty input','קלט ריק','assert index_users([]) == {}')]),
  'functions':exercise('safe-average','Safe average','ממוצע בטוח','Implement average(values). Return 0 for an empty list and the arithmetic mean otherwise.','ממשו average(values). החזירו 0 לרשימה ריקה ואת הממוצע החשבוני בכל מקרה אחר.','def average(values):\n    # Write your solution\n    pass',[test('Normal values','ערכים רגילים','assert average([10, 20, 30]) == 20'),test('Empty values','רשימה ריקה','assert average([]) == 0'),test('Negative values','ערכים שליליים','assert average([-10, 10]) == 0')]),
  'errors':exercise('parse-port','Validate a port','אמתו מספר Port','Implement parse_port(value). Convert a string to int. Raise ValueError when it is outside 1-65535.','ממשו parse_port(value). המירו מחרוזת ל-int. זרקו ValueError כשהערך מחוץ לטווח 1-65535.','def parse_port(value):\n    # Write your solution\n    pass',[test('Valid port','Port תקין','assert parse_port("8000") == 8000'),test('Too high','גבוה מדי','\ntry:\n parse_port("70000")\n assert False\nexcept ValueError: pass'),test('Not a number','אינו מספר','\ntry:\n parse_port("abc")\n assert False\nexcept ValueError: pass')]),
  'classes':exercise('bank-account','Protect account state','הגנו על מצב החשבון','Complete Account. deposit must reject non-positive amounts. withdraw must reject amounts above the balance.','השלימו את Account. המתודה deposit צריכה לדחות סכום שאינו חיובי ו-withdraw צריכה לדחות סכום גבוה מהיתרה.','class Account:\n    def __init__(self, balance=0):\n        self.balance = balance\n\n    def deposit(self, amount):\n        pass\n\n    def withdraw(self, amount):\n        pass',[test('Deposit','הפקדה','a=Account(10); a.deposit(15); assert a.balance==25'),test('Withdrawal','משיכה','a=Account(50); a.withdraw(20); assert a.balance==30'),test('Invalid state','מצב לא תקין','\na=Account(10)\ntry:\n a.withdraw(11)\n assert False\nexcept ValueError: pass\nassert a.balance==10')]),
  'dataclasses':exercise('money-value','Create a value object','צרו אובייקט ערך','Create a frozen Money dataclass with amount and currency fields.','צרו dataclass קבוע בשם Money עם השדות amount ו-currency.','from dataclasses import dataclass\n\n# Write Money here',[test('Construction','יצירה','m=Money(10,"ILS"); assert m.amount==10 and m.currency=="ILS"'),test('Value equality','שוויון ערכים','assert Money(10,"ILS") == Money(10,"ILS")'),test('Immutable','אינו משתנה','\nm=Money(10,"ILS")\ntry:\n m.amount=20\n assert False\nexcept Exception: pass')]),
  'pydantic-models':exercise('validated-user','Validate a user','אמתו משתמש','Create UserCreate with name of at least 2 characters and age from 13 through 120.','צרו UserCreate עם שם באורך שני תווים לפחות וגיל בין 13 ל-120.','from pydantic import BaseModel, Field\n\nclass UserCreate(BaseModel):\n    # Add fields and constraints\n    pass',[test('Valid user','משתמש תקין','u=UserCreate(name="Maya",age=24); assert u.name=="Maya"'),test('Short name rejected','שם קצר נדחה','\ntry:\n UserCreate(name="M",age=24)\n assert False\nexcept Exception: pass'),test('Age rejected','גיל נדחה','\ntry:\n UserCreate(name="Maya",age=12)\n assert False\nexcept Exception: pass')],['pydantic']),
  'testing-concepts':exercise('business-rule','Make the tests pass','גרמו לבדיקות לעבור','Implement can_publish(user). A user may publish only when active, verified and at least 18.','ממשו can_publish(user). משתמש רשאי לפרסם רק כאשר הוא פעיל, מאומת וגילו לפחות 18.','def can_publish(user):\n    # Implement the business rule\n    pass',[test('Eligible user','משתמש מורשה','assert can_publish({"active":True,"verified":True,"age":18}) is True'),test('Inactive user','משתמש לא פעיל','assert can_publish({"active":False,"verified":True,"age":30}) is False'),test('Minor user','משתמש קטין','assert can_publish({"active":True,"verified":True,"age":17}) is False')])
};
function test(en,he,code){return{en,he,code}}
function exercise(id,en,he,instructionsEn,instructionsHe,starterCode,tests,packages=[]){return{id,en,he,instructionsEn,instructionsHe,starterCode,tests,packages}}
