export const installGuides={
  'install-git':guide('Install once, verify immediately','מתקינים פעם אחת ומוודאים מיד',[
    step('Download Git for Windows','הורידו Git for Windows','Use the official Git download page. Choose the 64-bit installer unless the computer specifically uses Windows on ARM.','השתמשו בעמוד ההורדה הרשמי של Git. בחרו ב-Installer של 64 ביט, אלא אם המחשב מריץ Windows on ARM.','','https://git-scm.com/download/win'),
    step('Important installer choices','בחירות חשובות בהתקנה','Keep Git Credential Manager enabled. Allow Git from the command line and third-party software. The remaining defaults are suitable for this course.','השאירו את Git Credential Manager פעיל. אפשרו שימוש ב-Git משורת הפקודה ומתוכנות נוספות. שאר ברירות המחדל מתאימות לקורס.'),
    step('Configure commit identity','הגדירו זהות ל-Commit','Use your real display name and an email address verified in GitHub. These values become part of future commits.','השתמשו בשם התצוגה שלכם ובכתובת אימייל שאומתה ב-GitHub. הערכים האלו הופכים לחלק מה-Commits העתידיים.','git config --global user.name "YOUR NAME"\ngit config --global user.email "YOUR_EMAIL"'),
    step('Verify Git','בדקו את Git','Open a new PowerShell window. A version number confirms that Windows can find Git through PATH.','פתחו חלון PowerShell חדש. מספר גרסה מאשר ש-Windows מוצא את Git דרך PATH.','git --version\ngit config --global --list')]),
  'install-uv-python':guide('One tool owns Python','כלי אחד מנהל את Python',[
    step('Install uv','התקינו uv','Run the official standalone installer in PowerShell. The command temporarily bypasses the script execution policy only for this installation process.','הריצו את ה-Installer הרשמי ב-PowerShell. הפקודה עוקפת זמנית את מדיניות הרצת הסקריפטים רק לצורך ההתקנה.','powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"','https://docs.astral.sh/uv/getting-started/installation/'),
    step('Restart PowerShell','פתחו PowerShell מחדש','Close every open terminal and open a new PowerShell window so the updated PATH is loaded.','סגרו את כל חלונות ה-Terminal ופתחו PowerShell חדש כדי לטעון את PATH המעודכן.','uv --version'),
    step('Install Python with uv','התקינו Python באמצעות uv','Let uv install the project Python version. Do not download a separate Python installer for this trail.','אפשרו ל-uv להתקין את גרסת Python של הפרויקט. אין להוריד Installer נפרד של Python עבור המסלול.','uv python install 3.12\nuv python list'),
    step('Prove Python runs','ודאו ש-Python רץ','uv can execute Python even when the global python command is not configured. This keeps project tooling predictable.','uv יכול להריץ Python גם כאשר הפקודה הגלובלית python אינה מוגדרת. כך כלי הפרויקט נשארים צפויים.','uv run python --version')]),
  'github-account-repo':guide('Create the remote home first','יוצרים קודם בית מרוחק',[
    step('Create a GitHub account','צרו חשבון GitHub','Open GitHub, select Sign up and complete the account flow. Choose a professional username because it becomes part of repository and Pages URLs.','פתחו את GitHub, בחרו Sign up והשלימו את יצירת החשבון. בחרו שם משתמש מקצועי, מפני שהוא הופך לחלק מכתובות ה-Repository והאתר.','','https://github.com/signup'),
    step('Verify the email address','אמתו את כתובת האימייל','Open the verification email from GitHub. An unverified address can block basic actions such as creating a repository.','פתחו את הודעת האימות של GitHub. כתובת שלא אומתה עלולה לחסום פעולות בסיסיות כמו יצירת Repository.','','https://docs.github.com/en/account-and-profile/how-tos/email-preferences/verifying-your-email-address'),
    step('Create an empty repository','צרו Repository ריק','Select the plus menu, New repository, name it hagpy-first-site and choose Public. Do not add README, .gitignore or a license because the local project will provide the first commit.','פתחו את תפריט הפלוס, בחרו New repository, קראו לו hagpy-first-site ובחרו Public. אל תוסיפו README, ‏.gitignore או License, מפני שהפרויקט המקומי יספק את ה-Commit הראשון.','Name: hagpy-first-site\nVisibility: Public\nAdd README: No\n.gitignore: None\nLicense: None','https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository'),
    step('Copy the HTTPS URL','העתיקו את כתובת ה-HTTPS','Keep the Quick setup page open and copy the HTTPS URL. Replace USERNAME in later commands with your GitHub username.','השאירו את עמוד Quick setup פתוח והעתיקו את כתובת ה-HTTPS. בפקודות הבאות החליפו USERNAME בשם המשתמש שלכם.','https://github.com/USERNAME/hagpy-first-site.git')]),
  'verify-installation':guide('Do not continue with a broken setup','לא ממשיכים עם התקנה שבורה',[
    step('Open a fresh terminal','פתחו Terminal חדש','Close every terminal, then open PowerShell again. This prevents an old process from using an outdated PATH.','סגרו את כל חלונות ה-Terminal ואז פתחו PowerShell מחדש. כך תהליך ישן לא ישתמש ב-PATH שאינו מעודכן.'),
    step('Run the complete check','הריצו את הבדיקה המלאה','Every command must print a version and return to the prompt without an error. The exact version numbers may be newer than the examples in the course.','כל פקודה צריכה להדפיס גרסה ולחזור לשורת הפקודה ללא שגיאה. מספרי הגרסאות בפועל עשויים להיות חדשים יותר מהדוגמאות בקורס.','git --version\nuv --version\nuv run python --version'),
    step('Confirm Git identity','בדקו את זהות Git','Both values must be present before the first commit. Use the same verified email associated with GitHub.','שני הערכים חייבים להיות קיימים לפני ה-Commit הראשון. השתמשו באותה כתובת מאומתת שמשויכת ל-GitHub.','git config --global user.name\ngit config --global user.email'),
    step('Success condition','תנאי הצלחה','Continue only after all five values are printed: three tool versions, a name and an email address.','המשיכו רק לאחר שהודפסו חמישה ערכים: שלוש גרסאות כלים, שם וכתובת אימייל.')]),
  'project-setup':guide('Create the first project folder','מקימים את הפרויקט הראשון',[
    step('Go to the workspace folder','עברו לתיקיית העבודה','Start from the simple workspace path created earlier. Keeping course projects together makes paths, commands and screenshots easier to compare.','התחילו מנתיב העבודה הפשוט שיצרתם קודם. שמירת פרויקטי הקורס יחד הופכת נתיבים, פקודות וצילומי מסך לקלים יותר להשוואה.','cd C:\\AI-DEV-2026'),
    step('Initialize the project with uv','אתחלו את הפרויקט באמצעות uv','Create a minimal uv project without Git. The --bare option creates only pyproject.toml, while --vcs none leaves Git initialization for the GitHub lesson.','צרו פרויקט uv מינימלי ללא Git. האפשרות --bare יוצרת רק pyproject.toml, והאפשרות --vcs none משאירה את אתחול Git לשיעור GitHub.','uv init --bare --vcs none hagpy-first-site','https://docs.astral.sh/uv/reference/cli/#uv-init'),
    step('Enter the project folder','היכנסו לתיקיית הפרויקט','Commands that create files must run from inside the project folder. Verify that pyproject.toml exists before continuing.','פקודות שיוצרות קבצים צריכות לרוץ מתוך תיקיית הפרויקט. ודאו ש-pyproject.toml קיים לפני שממשיכים.','cd hagpy-first-site\ndir'),
    step('Open the project in your editor','פתחו את הפרויקט בעורך שלכם','Open the project root in the editor of your choice. Confirm that pyproject.toml appears at the top level before editing files.','פתחו את שורש הפרויקט בעורך לבחירתכם. ודאו שהקובץ pyproject.toml מופיע ברמה העליונה לפני עריכת קבצים.')]),
  'first-html-site':guide('Build the first local page','בונים את העמוד המקומי הראשון',[
    step('Create index.html','צרו index.html','In your editor, create index.html at the project root. Paste the complete document and save it.','בעורך שבחרתם, צרו את index.html בשורש הפרויקט. הדביקו את המסמך המלא ושמרו אותו.','<!doctype html>\n<html lang="he" dir="rtl">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>האתר הראשון שלי</title>\n</head>\n<body>\n  <h1>האתר הראשון שלי באוויר</h1>\n  <p>נבנה במסלול HagPy.</p>\n</body>\n</html>'),
    step('Preview through HTTP','הריצו תצוגה מקומית','Run a local server from the project directory. Keep the terminal open and browse to the local address. Stop the server later with Ctrl + C.','הריצו שרת מקומי מתוך תיקיית הפרויקט. השאירו את ה-Terminal פתוח וגלשו לכתובת המקומית. לאחר מכן עצרו את השרת באמצעות Ctrl + C.','uv run python -m http.server 8000\n# Open http://localhost:8000'),
    step('Verify before Git','בדקו לפני Git','The browser must show the Hebrew heading. If it does not, confirm that the file is named exactly index.html and that PowerShell is in the correct directory.','הדפדפן חייב להציג את הכותרת בעברית. אם לא, ודאו שהקובץ נקרא בדיוק index.html וש-PowerShell נמצא בתיקייה הנכונה.')]),
  'push-first-repository':guide('From files to history','מקבצים להיסטוריה',[
    step('Initialize local Git','אתחלו Git מקומי','Run these commands from inside hagpy-first-site. git status should show index.html as an untracked file.','הריצו את הפקודות מתוך hagpy-first-site. הפקודה git status צריכה להציג את index.html כקובץ שאינו במעקב.','git init\ngit status'),
    step('Create the first commit','צרו Commit ראשון','Stage the files, inspect the status and commit one coherent change.','הוסיפו את הקבצים ל-Staging, בדקו את המצב וצרו Commit אחד מלוכד.','git add .\ngit status\ngit commit -m "Create first website"\ngit branch -M main'),
    step('Connect the remote repository','חברו את ה-Repository המרוחק','Use the HTTPS URL copied from GitHub. Verify origin before pushing.','השתמשו בכתובת ה-HTTPS שהעתקתם מ-GitHub. ודאו את origin לפני ההעלאה.','git remote add origin https://github.com/USERNAME/hagpy-first-site.git\ngit remote -v','https://docs.github.com/en/get-started/git-basics/managing-remote-repositories'),
    step('Push main','העלו את main','Push the commit. Git Credential Manager may open the browser for GitHub authentication. Complete it and return to PowerShell.','העלו את ה-Commit. ‏Git Credential Manager עשוי לפתוח את הדפדפן לצורך אימות ב-GitHub. השלימו אותו וחזרו ל-PowerShell.','git push -u origin main'),
    step('Verify on GitHub','בדקו ב-GitHub','Refresh the repository page. It must show index.html and the Create first website commit.','רעננו את עמוד ה-Repository. הוא חייב להציג את index.html ואת ה-Commit בשם Create first website.')]),
  'publish-github-pages':guide('Turn a repository into a website','הופכים Repository לאתר',[
    step('Open Pages settings','פתחו את הגדרות Pages','Open the hagpy-first-site repository, select Settings and then Pages under Code and automation.','פתחו את hagpy-first-site, בחרו Settings ולאחר מכן Pages תחת Code and automation.','','https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site'),
    step('Choose the publishing source','בחרו מקור פרסום','Under Build and deployment select Deploy from a branch. Choose main and /(root), then Save.','תחת Build and deployment בחרו Deploy from a branch. בחרו main ו-/(root), ואז Save.','Source: Deploy from a branch\nBranch: main\nFolder: /(root)'),
    step('Wait for deployment','המתינו לפרסום','GitHub creates a Pages deployment. The first deployment usually takes a few minutes and can sometimes take longer. Do not repeatedly change the settings.','GitHub יוצר פרסום של Pages. הפרסום הראשון נמשך בדרך כלל מספר דקות ולעיתים יותר. אל תשנו את ההגדרות שוב ושוב.'),
    step('Open the live URL','פתחו את האתר החי','The project site normally uses this address. Replace USERNAME with the account name. Repository names and paths are case-sensitive.','אתר הפרויקט משתמש בדרך כלל בכתובת הזו. החליפו USERNAME בשם החשבון. שמות Repository ונתיבים רגישים לאותיות גדולות וקטנות.','https://USERNAME.github.io/hagpy-first-site/'),
    step('Publish the next change','פרסמו שינוי נוסף','Edit index.html, commit and push. GitHub Pages will automatically publish the new main commit.','ערכו את index.html, בצעו Commit ו-Push. ‏GitHub Pages יפרסם אוטומטית את ה-Commit החדש של main.','git add index.html\ngit commit -m "Update homepage"\ngit push')]),
  'setup-troubleshooting':guide('Diagnose, do not reinstall blindly','מאבחנים, לא מתקינים מחדש בעיוורון',[
    step('Command not recognized','הפקודה אינה מזוהה','Close and reopen PowerShell first. Then ask Windows where the executable is. If no path is printed, reinstall only the missing tool.','ראשית סגרו ופתחו מחדש את PowerShell. לאחר מכן שאלו את Windows היכן נמצא קובץ ההרצה. אם לא מודפס נתיב, התקינו מחדש רק את הכלי החסר.','where.exe git\nwhere.exe uv\nwhere.exe code'),
    step('Git asks who you are','Git מבקש זהות','Configure both values and run the commit again. The email should match a verified GitHub email.','הגדירו את שני הערכים והריצו שוב את ה-Commit. כתובת האימייל צריכה להתאים לכתובת מאומתת ב-GitHub.','git config --global user.name "YOUR NAME"\ngit config --global user.email "YOUR_EMAIL"'),
    step('Remote origin already exists','origin כבר קיים','Inspect the existing address. Change it instead of adding a second origin.','בדקו את הכתובת הקיימת. שנו אותה במקום להוסיף origin נוסף.','git remote -v\ngit remote set-url origin https://github.com/USERNAME/hagpy-first-site.git'),
    step('Push rejected','ה-Push נדחה','Confirm that the GitHub repository was created empty. If it contains an initial README, do not use force. For a first course project, create a new empty repository and connect its URL.','ודאו שה-Repository ב-GitHub נוצר ריק. אם הוא מכיל README התחלתי, אל תשתמשו ב-Force. בפרויקט הראשון בקורס, צרו Repository ריק חדש וחברו את כתובתו.'),
    step('Pages shows 404','Pages מציג 404','Confirm the repository is Public, index.html is at the selected root, Pages uses main and /(root), and the URL ends with the repository name. Check the Actions tab for a failed pages build.','ודאו שה-Repository ציבורי, שהקובץ index.html נמצא בשורש שנבחר, ש-Pages משתמש ב-main וב-/(root) ושהכתובת מסתיימת בשם ה-Repository. בדקו ב-Actions אם פרסום Pages נכשל.'),
    step('Capture useful evidence','אספו מידע שימושי','Before asking for help, copy the exact error and these command results. Do not send passwords, tokens or browser authentication codes.','לפני שמבקשים עזרה, העתיקו את השגיאה המדויקת ואת תוצאות הפקודות. אל תשלחו סיסמאות, Tokens או קודי אימות מהדפדפן.','git --version\nuv --version\nuv run python --version\ngit status\ngit remote -v')])
};
function guide(en,he,steps){return{en,he,steps}}
function step(en,he,bodyEn,bodyHe,code='',link=''){return{en,he,bodyEn,bodyHe,code,link}}
